### ISSUE TITLE
Karma-coverage always shows 100%

### ISSUE THREAD

**Issue by NoHomey** [karma-runner/karma-coverage#201]
I'm having hard time making karma-coverage to report right results, it always shows 100%

This is my karma.conf.coffee file:

```
module.exports = (config) ->
  config.set
    basePath: ""
    frameworks: ["jasmine"]
    files: [
      "test.js"
      "test_spec.js"
    ]
    exclude: []
    preprocessors: {}
    reporters: ["progress", "coverage"]
    preprocessors:
      "test.js": ["coverage"]
    coverageReporter:
      type : "html",
      dir : "coverage/"
    port: 9876
    colors: true
    logLevel: config.LOG_INFO
    autoWatch: false
    browsers: ["Chrome"]
    singleRun: true
    concurrency: Infinity
```

test.js:

```
function test(a) {
	return a
}
```

test_spec.js:
```
describe("test", function() {
  it("it tests", function() {
    expect(test(3)).toEqual(4);
  });
});
```

karma output:
```
karma start
31 12 2015 17:23:14.674:INFO [karma]: Karma v0.13.16 server started at http://localhost:9876/
31 12 2015 17:23:14.684:INFO [launcher]: Starting browser Chrome
31 12 2015 17:23:16.019:INFO [Chrome 47.0.2526 (Linux 0.0.0)]: Connected on socket 5BCBhSrzsbgS53LgAAAA with id 93241680
Chrome 47.0.2526 (Linux 0.0.0) test it tests FAILED
	Expected 3 to equal 4.
	    at Object.<anonymous> (/home/ivo/ivo/diplomna3/test_spec.js:3:21)
Chrome 47.0.2526 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.024 secs / 0.005 secs)
```

And finally coverage results:

![test](https://cloud.githubusercontent.com/assets/8791438/12065680/169b4088-afe4-11e5-8a42-7c026a4d7b12.png)
